    name: GitHub Classroom Workflow

    on: [push]

    jobs:
      build:
        name: Autograding
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v2
          - uses: actions/setup-python@v2
            with:
              python-version: '3.8'
          - name: Install Dependencies
            run: |
              python -m pip install -r requirements.txt
          - uses: education/autograding@v1
